### ISSUE TITLE
Make Configuration External

### ISSUE THREAD

**Issue by pipebaum** [innoventsolutions/BIRT-Report-Runner-REST-Service#2]
Figure out a better way of handling configuration to work in conjunctions with Application.properties.

Do we want to use application.properties or do we want to have our own configuration file that overrides application.properties.

**Comment by pipebaum** [comment]
Perhaps better approach is just make application.properties external.

**Comment by SteveSchafer-Innovent** [comment]
All properties have been moved to application.properties with the new ConfigService class.  All properties have reasonable defaults because many properties are required for unit tests and the aim is to be able to build with maven, including unit tests, without having to modify any properties.

Spring includes several mechanisms for externalizing application.properties.  The simplest is to use the --spring.config.location command line argument.
